### ISSUE TITLE
MVP - DSL support for defining packages

### ISSUE THREAD

**Issue by bjelicaluka** [albertmakan/nft-specific-language#1]
**Is your feature part of a bigger picture? If yes, which one?**
DSL

**Describe the overall flow of the feature from the user's perspective**
1. A developer wants to create a new package, using an existing Solidity contract:
 - contract can be referenced from local FS or as an external resource (URL of some sort)
2. A developer wants to create a new package, using his custom/new logic for defining specifics:
 - in this case, we need to support a way to define packages by writing custom Solidity code in combination with our DSL
 - or we can support defining a local Solidity contract and using it as in option 1

**Provide a list of steps required to implement the feature**
- [x] Syntax (as a team)
- [x] Extract data from solidity code (as much as possible)
- [x] Integrate existing packages into package
- [x] Syntactic check
- [x] Code Generation

**Additional context (optional)**

This is for option 2 case 1
<div align="center">
<img src="https://user-images.githubusercontent.com/55081607/220599657-cdd8849f-c803-43ed-a651-e1d3d64fe3cc.png"/></div>

**Comment by panicmilos** [comment]
With the merge of #9 we can consider this issue as Done.

**Comment by panicmilos** [comment]
Reopening issue in order to fix:
- imports from .sol file
- missing @global in exported package

**Comment by panicmilos** [comment]
With the merge of #19 we can consider the fixes as Done.
