### ISSUE TITLE
MVP - Website, Search app and Documentation

### ISSUE THREAD

**Issue by bjelicaluka** [albertmakan/nft-specific-language#15]
**Is your feature part of a bigger picture? If yes, which one?**
Yes, Product Documentation

**Describe the overall flow of the feature from the user's perspective**
As a Solidity developer, I want to read the docs about this tool, so that I can understand how to use it.
As a Solidity developer, I want to have a UI for searching the packages, so that I can find what I need more easily.
As a Solidity developer, I want to understand the purpose of this tool quickly, so that I can decide if I need it.

**Provide a list of steps required to implement the feature**
- [x] Implement a nice landing page that presents the tool
- [x] Implement SPM documentation
- [x] Implement SPL documentation
- [x] Implement UI for searching packages

**Additional context (optional)**
/

**Comment by panicmilos** [comment]
With the merge of #22, we can consider this issue as Done.
Documentation is online at: https://spm.bjelicaluka.com/
