### ISSUE TITLE
MVP - Autocomplete + IntelliSense

### ISSUE THREAD

**Issue by bjelicaluka** [albertmakan/nft-specific-language#2]
**Is your feature part of a bigger picture? If yes, which one?**
DSL

**Describe the overall flow of the feature from the user's perspective**
- Autocomplete and IntelliSense for DSL
- Autocomplete import paths
- BONUS - autocomplete remote packages

**Provide a list of steps required to implement the feature**
- [x] Implement highlighting
- [x] Implement code snippets
- [x] Setup LSP project
- [x] Implement autocomplete for imports
- [x] Implement autocomplete for exports
- [x] Deploy extension

**Additional context (optional)**

**Comment by panicmilos** [comment]
With the merge of #20, we can consider this issue as Done.
Extension can be found on: https://marketplace.visualstudio.com/items?itemName=Siithub.spm
