### ISSUE TITLE
MVP - DSL package integration support

### ISSUE THREAD

**Issue by bjelicaluka** [albertmakan/nft-specific-language#3]
**Is your feature part of a bigger picture? If yes, which one?**
DSL

**Describe the overall flow of the feature from the user's perspective**
- DSL should support importing packages
- DSL should support defining Contract Administration specifics
- DSL should support defining Token Handling specifics

**Provide a list of steps required to implement the feature**
- [x] Syntax (as a team)
- [x] Code Generation

**Additional context (optional)**
<img width="576" alt="image" src="https://user-images.githubusercontent.com/52993990/217516480-6a955e39-8c79-4acd-a520-320d94ca76fe.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/52993990/217516596-85745c3f-1d0e-446f-89db-8a6fdbdfe1ae.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/52993990/217516640-34941fd6-eaa0-4186-99da-d4421d932799.png">

**Comment by albertmakan** [comment]
With the merge of #13 and #18, we can consider this issue as Done.
