### ISSUE TITLE
MVP - DSL support for defining single or multi-contract code generation outputs

### ISSUE THREAD

**Issue by bjelicaluka** [albertmakan/nft-specific-language#4]
**Is your feature part of a bigger picture? If yes, which one?**
DSL

**Describe the overall flow of the feature from the user's perspective**
- Support for defining single-contract code generation outputs
- Support for defining multi-contract code generation outputs

**Provide a list of steps required to implement the feature**
- [x] Syntax
- [x] Semantics
- [x] Code Generation

**Additional context (optional)**

**Comment by albertmakan** [comment]
With the merge of #13 we can consider this issue as Done.
