### ISSUE TITLE
MVP - DSL Support for versioning packages

### ISSUE THREAD

**Issue by bjelicaluka** [albertmakan/nft-specific-language#5]
**Is your feature part of a bigger picture? If yes, which one?**
DSL

**Describe the overall flow of the feature from the user's perspective**
- DSL support for versioning packages

**Provide a list of steps required to implement the feature**
- [x] Support incrementing version
- [x] Keep version locally
- [x] Validate version on the Registry

**Additional context (optional)**

**Comment by panicmilos** [comment]
Closing this issue as it is Done on the fly in #6 and #8.
