### ISSUE TITLE
MVP - CLI support for packages

### ISSUE THREAD

**Issue by bjelicaluka** [albertmakan/nft-specific-language#6]
**Is your feature part of a bigger picture? If yes, which one?**
CLI

**Describe the overall flow of the feature from the user's perspective**
- Support for running commands that will help users to create, install or deploy packages.

**Provide a list of steps required to implement the feature**
- [x] Init package project command
- [x] Install package command (all from package.json and single package)
- [x] Compile package project command
- [x] Deploy package command

**Additional context (optional)**
Packages should work and be stored similarly to npm packages.

**Comment by panicmilos** [comment]
With the merge of #10, we can consider this issue as Done.

**Comment by panicmilos** [comment]
Reopening this issue in order to fix the signature.

**Comment by panicmilos** [comment]
With the merge of #12, we can consider this issue as Done.
