### ISSUE TITLE
MVP - CLI support for package integration

### ISSUE THREAD

**Issue by bjelicaluka** [albertmakan/nft-specific-language#7]
**Is your feature part of a bigger picture? If yes, which one?**
CLI

**Describe the overall flow of the feature from the user's perspective**
Support for running commands that will help users to integrate packages into single or multiple contracts.

**Provide a list of steps required to implement the feature**
- [x] Init package integration project
- [x] Compile package integration into solidity output

**Additional context (optional)**

**Comment by albertmakan** [comment]
With the merge of #16, we can consider this issue as Done.
